export const SETTINGS_DEFAULTS: Record<string, string> = {
  // ── Modules (activables/désactivables depuis l'admin) ───
  module_blog_enabled:          'true',
  module_ai_generation_enabled: 'true',
  module_events_enabled:        'true',
  module_newsletter_enabled:    'true',
  module_decodeur_enabled:      'true',
  module_social_enabled:        'true',

  // ── IA & Budget (admin > Paramètres > IA & Budget) ──────
  // Modèle Claude utilisé par toutes les générations ; voir src/constants/aiModels.ts.
  ai_model:                 'claude-opus-5',
  // Niveau de réflexion : low | medium | high (levier de coût principal).
  ai_effort:                'medium',
  // Budget mensuel indicatif en USD ; '0' désactive l'alerte.
  ai_budget_monthly_usd:    '0',
  // Pourcentage du budget à partir duquel l'admin affiche une alerte.
  ai_budget_alert_percent:  '80',

  // ── Activité, Ligne Éditoriale & Marque (admin > Paramètres > Éditorial & Marque) ──
  site_activity_context: "Emmanuelle Esthétique — Institut de beauté et soins esthétiques spécialisé dans les soins du visage, la relaxation et le bien-être à Palézieux, Vaud.",
  site_target_persona:      "Hommes et femmes de 25 à 45 ans, actifs, dont la vie personnelle ou professionnelle est parasitée par une relation destructrice (en couple, en phase de séparation ou en reconstruction post-rupture). Douleurs : érosion lente de l'identité, brouillard mental (gaslighting), culpabilité étouffante, hypervigilance et épuisement biologique. Besoins : valider leur réalité, clarté immédiate, protocole de défense concret, sevrage neuro-émotionnel et immunisation.",
  site_tone_of_voice:        "Voix conversationnelle, directe et chirurgicale, comme un praticien qui parle en cabinet face à son interlocuteur. Pas de prose littéraire ni de formules ronflantes. Tutoiement thérapeutique ('tu') pour créer une proximité immédiate et briser l'isolement. Mentor expert et lucide avec une longueur d'avance. Bienveillant et sécurisant, sans jamais infantiliser ni victimiser. Validation des ressentis du lecteur avant affirmation. Emploi naturel du 'ça' et des marqueurs de proximité orale.",
  site_brand_tone:           "Promesse centrale : 'Décoder les mécanismes de l'emprise, briser le brouillard mental et appliquer l'Arsenal Tactique pour reprendre définitivement le contrôle de ton avenir.' Vocabulaire privilégié : Coach relation toxique, Pervers narcissique, Arsenal tactique, Protocole de défense, Sevrage neuro-émotionnel, Brouillard mental, Gaslighting, Inversion de culpabilité, Contre-stratégie, Hypervigilance, Rupture sécurisée, Immunisation. Mots interdits : termes corporate/flous (optimiser, booster, synergies, écosystème), jargon ésotérique ou victimisation passive.",
  site_blog_topics:          "1. Profils toxiques & décodage clinique (analyse de la psyché des manipulateurs, pervers narcissiques et structures psychotiques)\n2. Brouillard mental & gaslighting (inversion de culpabilité, déconstruction des pièges et de la confusion)\n3. Protocole de défense & contre-communication (scripts de communication de crise, méthode de la roche grise, limites fermes, rupture sécurisée)\n4. Trauma & sevrage neuro-émotionnel (addiction biologique à la relation, gestion du manque et des ancrages neuro-biologiques)\n5. Reconstruction identitaire & estime de soi (guérison de l'enfant intérieur, souveraineté et réalignement des valeurs)\n6. Immunisation définitive (détection précoce des prédateurs, reprogrammation des schémas inconscients)",

  // ── Coordonnées d'entreprise (admin > Paramètres > Entreprise) ──
  business_name: 'Emmanuelle Esthétique',
  business_owner: 'Emmanuelle',
  business_email: 'contact@emmanuelle-esthetique.com',
  business_phone: '+41 79 000 00 00',
  business_address_street:  '',
  business_address_postal:  '',
  business_address_city: 'Palézieux, Vaud',
  business_address_region:  'Vaud',
  business_address_country: 'CH',
  business_price_range:     'CHF 450–CHF 1295',

  // ── Hero global ─────────────────────────────────────────
  hero_image:       '/images/hero-1400.jpg',
  hero_text_color:  'dark',
  global_logo:      '',
  favicon_url:      '',

  // ── Accueil ─────────────────────────────────────────────
  home_coaching_hero_badge:       'Coaching Relation Toxique',
  home_coaching_hero_title:       'Comprendre l\'Emprise, Briser les Chaînes et Se Reconstruire',
  home_coaching_hero_subtitle:    'Tu as longtemps cru que le problème venait de toi. Aujourd\'hui, la confusion laisse place à une certitude : tu es ou tu as été sous emprise. Ne reste plus seul(e) face au doute. Bénéficie d\'un accompagnement pragmatique, direct et orienté résultats pour décoder les mécanismes de manipulation, poser des limites infranchissables et reprendre définitivement les commandes de ta vie.',
  home_coaching_hero_cta:         'RÉSERVER MA SESSION STRATÉGIQUE OFFERTE',
  home_coaching_hero_disclaimer:  'Échange de 30 minutes, strictement confidentiel, sécurisé et sans aucun engagement.',

  home_coaching_media_eyebrow:    'Au-delà des Chaînes',
  home_coaching_media_title:      'L\'Expertise Multimédia au Service de ta Clarté',
  home_coaching_media_desc:       'Avant d\'engager un changement ou de poser un acte de rupture, tu as besoin de certitudes et de clés de décodage. À travers mes canaux d\'analyse, je décortique chaque semaine les profils complexes et les dynamiques de manipulation psychologique pour t\'apporter des réponses là où régnait le chaos.',
  home_coaching_podcast_title:    '🎙️ Le Podcast "Au-delà des Chaînes"',
  home_coaching_podcast_desc:     'L\'espace audio immersif pour plonger en profondeur dans les mécaniques invisibles de l\'emprise. Des épisodes denses et sans tabou pour comprendre la psyché des manipulateurs, analyser le trauma et entamer un sevrage émotionnel durable.',
  home_coaching_podcast_cta:      'Écouter sur Apple Podcast & Spotify',
  home_coaching_youtube_title:    '📺 La Chaîne YouTube',
  home_coaching_youtube_desc:     'Des analyses cliniques et des décryptages chirurgicaux des personnalités toxiques, perverses et des structures psychotiques. Des vidéos concrètes et imagées pour cesser de douter de ta propre réalité et identifier les pièges comportementaux.',
  home_coaching_youtube_cta:      'Regarder les dernières analyses vidéo',

  home_coaching_frustrations_eyebrow: 'Reconnaître les Symptômes de l\'Emprise Psychologique',
  home_coaching_frustrations_title:   'Vivre ou avoir vécu aux côtés d\'une personnalité toxique, manipulatrice ou présentant une structure psychotique ne laisse aucune place au hasard. C\'est une érosion lente, invisible et méthodique de ton identité. Si tu te reconnais dans ces situations, sache que tu n\'es ni fou, ni paranoïaque :',
  home_coaching_frustrations_card1_title: 'La confusion permanente (Gaslighting)',
  home_coaching_frustrations_card1_desc:  'Tu réécris tes propres souvenirs, tu doutes de tes ressentis et tu finis par t\'excuser pour des fautes que tu n\'as pas commises.',
  home_coaching_frustrations_card2_title: 'La marche sur des œufs',
  home_coaching_frustrations_card2_desc:  'Ton quotidien est dicté par l\'humeur de l\'autre. Tu adaptes tes mots, tes choix, tes vêtements et tes comportements pour éviter la prochaine explosion ou le prochain silence punitif.',
  home_coaching_frustrations_card3_title: 'L\'isolement invisible',
  home_coaching_frustrations_card3_desc:  'Sans t\'en rendre compte, tu t\'es éloigné(e) de tes amis, de ta famille ou de tes passions pour te focaliser exclusivement sur la satisfaction d\'un pôle toxique insatiable.',
  home_coaching_frustrations_card4_title: 'L\'épuisement biologique',
  home_coaching_frustrations_card4_desc:  'Ton corps envoie des signaux d\'alerte massifs (insomnies, crises d\'angoisse, fatigue chronique, sensation d\'étouffement). Tu es en état d\'hypervigilance 24h/24.',
  home_coaching_frustrations_p1:          'La vérité brute : On ne guérit pas d\'une relation toxique par le simple passage du temps. On en guérit en comprenant les codes du bourreau et en appliquant une contre-stratégie implacable.',

  home_coaching_expertise_eyebrow: 'De la Clinique au Terrain',
  home_coaching_expertise_title:   'Pourquoi mon Approche fait Autorité',
  home_coaching_expertise_text1:   'Le marché de l\'accompagnement regorge de théories abstraites et de conseils génériques. Face à la perversion, à la manipulation fine ou à des profils psychotiques installés, la théorie pure s\'effondre. Mon expertise unique s\'appuie sur deux piliers indéboulonnables :',
  home_coaching_expertise_text2:   '6 ans d\'expérience en tant que Thérapeute : Durant ces années de pratique intense en cabinet, j\'ai disséqué la psyché humaine, soigné les traumas complexes et développé des protocoles précis de reconstruction identitaire. Je sais scientifiquement ce qu\'il se passe dans ton cerveau sous emprise.',
  home_coaching_expertise_text3:   'Une immersion personnelle depuis toujours : Les personnalités toxiques et les structures psychotiques ne sont pas pour moi des chapitres de manuels universitaires. Je les ai côtoyées, subies et analysées au sein même de ma propre structure familiale. Ce système, je l\'ai vécu dans ma chair. J\'en ai décodé les rouages secrets et j\'ai appris à m\'en libérer définitivement.',
  home_coaching_expertise_quote:   '« Je ne vais pas me contenter de t\'accueillir et de hocher la tête. Je sais exactement où fait mal le piège, je connais les verrous psychologiques de ton agresseur, et je possède la clé tactique pour les faire sauter. »',
  home_coaching_expertise_author:  'Matthieu Le Tousse',
  home_coaching_expertise_author_title: 'Ancien Thérapeute & Coach de Posture',

  home_coaching_prog_eyebrow: 'L\'Arsenal Tactique',
  home_coaching_prog_title:   'La Feuille de Route Stratégique pour Briser l\'Emprise',
  home_coaching_prog_desc:    'Un système d\'accompagnement complet et pas-à-pas, validé par mon expérience clinique et conçu pour te redonner tes armes psychologiques, émotionnelles et comportementales.',
  home_coaching_prog_module1_title: 'Module 1 : Le Point de Départ — Mindset Impénétrable',
  home_coaching_prog_module1_desc:  'Inversion immédiate de la polarité psychologique. Sortir définitivement du costume de victime passive pour endosser la posture d\'acteur souverain de ta délivrance. Reprendre les commandes absolues de ton flux de pensées et couper l\'accès à ta jauge émotionnelle.',
  home_coaching_prog_module2_title: 'Module 2 : Sortir du Brouillard Mental',
  home_coaching_prog_module2_desc:  'Dissipation de la confusion instillée par le manipulateur. Poser des concepts cliniques précis sur chaque agression, chaque inversion de culpabilité, pour valider ta propre réalité, poser des mots sur tes maux et cesser d\'auto-saboter tes jugements.',
  home_coaching_prog_module3_title: 'Module 3 : Le Protocole de Défense & Contre-Communication',
  home_coaching_prog_module3_desc:  'Mise en place de remparts comportementaux infranchissables. Apprentissage des techniques de communication de crisis (méthode de la roche grise, scripts de réponse courts) pour neutraliser, court-circuiter et désamorcer les attaques et provocations de la personnalité toxique au quotidien.',
  home_coaching_prog_module4_title: 'Module 4 : Le Sevrage Neuro-Émotionnel',
  home_coaching_prog_module4_desc:  'Briser l\'addiction biologique à la relation. L\'emprise crée un cycle de "shoots" chimiques destructeurs (alternance dopamine/cortisol). Ce module nettoie les ancrages neuro-biologiques profonds pour éteindre définitivement le manque, la nostalgie feinte et le risque de rechute.',
  home_coaching_prog_module5_title: 'Module 5 : Reconstruction de l\'Identité & Estime Blindée',
  home_coaching_prog_module5_desc:  'Redécouvrir qui tu es une fois le parasite relationnel extrait de ton système. Travail en profondeur de guérison sur l\'enfant intérieur, recollement des morceaux de l\'amour propre et réalignement total avec tes désirs, tes ambitions et tes valeurs fondamentales.',
  home_coaching_prog_module6_title: 'Module 6 : L\'Immunisation Définitive',
  home_coaching_prog_module6_desc:  'Création d\'un bouclier psychologique à vie. Reprogrammation de tes schémas inconscients pour détecter les profils prédateurs et manipulateurs à des kilomètres. Tu imposes tes limites de manière automatique, garantissant que plus jamais personne ne piétine ton territoire.',
  home_coaching_prog_cta:           'POSTULER AU PROGRAMME ARSENAL TACTIQUE',

  home_coaching_faq_eyebrow: 'Questions Fréquentes',
  home_coaching_faq_title:   'FAQ — Réponses Claires sur l\'Emprise et l\'Accompagnement',
  home_coaching_faq_q1:      'Comment savoir si je suis dans une relation toxique ou si le problème vient de moi ?',
  home_coaching_faq_r1:      'C’est la question centrale induite par la manipulation. Si vous passez votre temps à vous remettre en question, à ressentir une culpabilité sourde et à analyser frénétiquement les moindres variations d\'humeur de l\'autre pour éviter un conflit, vous êtes sous emprise. Le profil toxique ne se remet jamais en question. Le simple fait que vous vous posiez cette question est la preuve clinique que le dysfonctionnement ne vient pas de votre nature.',
  home_coaching_faq_q2:      'Quelle est la différence entre votre passé de thérapeute et ce coaching axé sur les résultats ?',
  home_coaching_faq_r2:      'La thérapie traditionnelle cherche principalement à comprendre le "pourquoi" et s\'inscrit souvent dans un temps long d\'introspection. Mon approche de coaching axée sur l\'Arsenal Tactique utilise mes 6 ans de bagage clinique pour identifier le mécanisme instantanément, mais bascule immédiatement sur le "comment". Nous mettons en place des protocoles d\'action, des scripts de communication et des verrous émotionnels pour obtenir des résultats factuels, mesurables et rapides.',
  home_coaching_faq_q3:      'Peut-on réellement se réparer après avoir partagé la vie d\'une personnalité psychotique ou perverse ?',
  home_coaching_faq_r3:      'Oui, absolument. Le traumatisme lié à une structure perverse ou psychotique agit comme un véritable piratage de votre système nerveux et cognitif. En appliquant un protocole strict de sevrage neuro-émotionnel et en reprogrammant vos schémas identitaires (les modules 4 et 5 de mon programme), vous pouvez non seulement retrouver votre état initial, mais développer une immunité et une clarté intérieures bien supérieures à celles que vous aviez avant la rencontre.',
  home_coaching_faq_q4:      'Mon ex-partenaire ou membre de ma famille est-il un pervers narcissique ou un psychotique ?',
  home_coaching_faq_r4:      'Poser un diagnostic psychiatrique formel demande du temps, mais les dynamiques destructrices restent identiques : absence totale d\'empathie, paranoïa constructive, inversion de la culpabilité, cycles de séduction et de destruction. Ensemble, durant nos sessions, nous analysons la typologie des comportements factuels pour adapter le protocole de défense le plus efficace possible, sans perdre de temps en spéculations stériles.',

  home_coaching_cta_title:   'Ne laisse plus un profil destructeur écrire les chapitres de ta vie',
  home_coaching_cta_desc:    'Chaque jour passé dans la confusion, le doute ou l\'attente d\'un changement qui n\'arrivera jamais est un jour volé à ta liberté et à ton avenir. Tu possèdes désormais la preuve qu\'un chemin clair, codifié et encadré par un professionnel qui a vécu cette réalité existe.',
  home_coaching_cta_invite:  'Le premier pas ne demande aucun courage, juste une décision : celle de parler à quelqu\'un qui te croit, qui te comprend, et qui sait exactement comment te sortir de là.',
  home_coaching_cta_button:  'DEMANDER MON ENTRETIEN STRATÉGIQUE PRIVÉ',

  home_hero_badge:       'Coaching Relation Toxique',
  home_hero_title:       'Comprendre l\'Emprise, Briser les Chaînes et Se Reconstruire',
  home_hero_subtitle:    'Tu as longtemps cru que le problème venait de toi. Aujourd\'hui, la confusion laisse place à une certitude : tu es ou tu as été sous emprise. Ne reste plus seul(e) face au doute. Bénéficie d\'un accompagnement pragmatique, direct et orienté résultats pour décoder les mécanismes de manipulation, poser des limites infranchissables et reprendre définitivement les commandes de ta vie.',
  home_hero_cta:         'RÉSERVER MA SESSION STRATÉGIQUE OFFERTE',
  home_hero_disclaimer:  'Échange de 30 minutes, strictement confidentiel, sécurisé et sans aucun engagement.',

  home_media_eyebrow:    'Au-delà des Chaînes',
  home_media_title:      'L\'Expertise Multimédia au Service de ta Clarté',
  home_media_desc:       'Avant d\'engager un changement ou de poser un acte de rupture, tu as besoin de certitudes et de clés de décodage. À travers mes canaux d\'analyse, je décortique chaque semaine les profils complexes et les dynamiques de manipulation psychologique pour t\'apporter des réponses là où régnait le chaos.',
  home_podcast_title:    '🎙️ Le Podcast "Au-delà des Chaînes"',
  home_podcast_desc:     'L\'espace audio immersif pour plonger en profondeur dans les mécaniques invisibles de l\'emprise. Des épisodes denses et sans tabou pour comprendre la psyché des manipulateurs, analyser le trauma et entamer un sevrage émotionnel durable.',
  home_podcast_cta:      'Écouter sur Apple Podcast & Spotify',
  home_youtube_title:    '📺 La Chaîne YouTube',
  home_youtube_desc:     'Des analyses cliniques et des décryptages chirurgicaux des personnalités toxiques, perverses et des structures psychotiques. Des vidéos concrètes et imagées pour cesser de douter de ta propre réalité et identifier les pièges comportementaux.',
  home_youtube_cta:      'Regarder les dernières analyses vidéo',

  home_frustrations_eyebrow: 'Reconnaître les Symptômes de l\'Emprise Psychologique',
  home_frustrations_title:   'Vivre ou avoir vécu aux côtés d\'une personnalité toxique, manipulatrice ou présentant une structure psychotique ne laisse aucune place au hasard. C\'est une érosion lente, invisible et méthodique de ton identité. Si tu te reconnais dans ces situations, sache que tu n\'es ni fou, ni paranoïaque :',
  home_frustrations_card1_title: 'La confusion permanente (Gaslighting)',
  home_frustrations_card1_desc:  'Tu réécris tes propres souvenirs, tu doutes de tes ressentis et tu finis par t\'excuser pour des fautes que tu n\'as pas commises.',
  home_frustrations_card2_title: 'La marche sur des œufs',
  home_frustrations_card2_desc:  'Ton quotidien est dicté par l\'humeur de l\'autre. Tu adaptes tes mots, tes choix, tes vêtements et tes comportements pour éviter la prochaine explosion ou le prochain silence punitif.',
  home_frustrations_card3_title: 'L\'isolement invisible',
  home_frustrations_card3_desc:  'Sans t\'en rendre compte, tu t\'es éloigné(e) de tes amis, de ta famille ou de tes passions pour te focaliser exclusivement sur la satisfaction d\'un pôle toxique insatiable.',
  home_frustrations_card4_title: 'L\'épuisement biologique',
  home_frustrations_card4_desc:  'Ton corps envoie des signaux d\'alerte massifs (insomnies, crises d\'angoisse, fatigue chronique, sensation d\'étouffement). Tu es en état d\'hypervigilance 24h/24.',
  home_frustrations_p1:          'La vérité brute : On ne guérit pas d\'une relation toxique par le simple passage du temps. On en guérit en comprenant les codes du bourreau et en appliquant une contre-stratégie implacable.',

  home_expertise_eyebrow: 'De la Clinique au Terrain',
  home_expertise_title:   'Pourquoi mon Approche fait Autorité',
  home_expertise_text1:   'Le marché de l\'accompagnement regorge de théories abstraites et de conseils génériques. Face à la perversion, à la manipulation fine ou à des profils psychotiques installés, la théorie pure s\'effondre. Mon expertise unique s\'appuie sur deux piliers indéboulonnables :',
  home_expertise_text2:   '6 ans d\'expérience en tant que Thérapeute : Durant ces années de pratique intense en cabinet, j\'ai disséqué la psyché humaine, soigné les traumas complexes et développé des protocoles précis de reconstruction identitaire. Je sais scientifiquement ce qu\'il se passe dans ton cerveau sous emprise.',
  home_expertise_text3:   'Une immersion personnelle depuis toujours : Les personnalités toxiques et les structures psychotiques ne sont pas pour moi des chapitres de manuels universitaires. Je les ai côtoyées, subies et analysées au sein même de ma propre structure familiale. Ce système, je l\'ai vécu dans ma chair. J\'en ai décodé les rouages secrets et j\'ai appris à m\'en libérer définitivement.',
  home_expertise_quote:   '« Je ne vais pas me contenter de t\'accueillir et de hocher la tête. Je sais exactement où fait mal le piège, je connais les verrous psychologiques de ton agresseur, et je possède la clé tactique pour les faire sauter. »',
  home_expertise_author:  'Matthieu Le Tousse',
  home_expertise_author_title: 'Ancien Thérapeute & Coach de Posture',

  home_prog_eyebrow: 'L\'Arsenal Tactique',
  home_prog_title:   'La Feuille de Route Stratégique pour Briser l\'Emprise',
  home_prog_desc:    'Un système d\'accompagnement complet et pas-à-pas, validé par mon expérience clinique et conçu pour te redonner tes armes psychologiques, émotionnelles et comportementales.',
  home_prog_module1_title: 'Module 1 : Le Point de Départ — Mindset Impénétrable',
  home_prog_module1_desc:  'Inversion immédiate de la polarité psychologique. Sortir définitivement du costume de victime passive pour endosser la posture d\'acteur souverain de ta délivrance. Reprendre les commandes absolues de ton flux de pensées et couper l\'accès à ta jauge émotionnelle.',
  home_prog_module2_title: 'Module 2 : Sortir du Brouillard Mental',
  home_prog_module2_desc:  'Dissipation de la confusion instillée par le manipulateur. Poser des concepts cliniques précis sur chaque agression, chaque inversion de culpabilité, pour valider ta propre réalité, poser des mots sur tes maux et cesser d\'auto-saboter tes jugements.',
  home_prog_module3_title: 'Module 3 : Le Protocole de Défense & Contre-Communication',
  home_prog_module3_desc:  'Mise en place de remparts comportementaux infranchissables. Apprentissage des techniques de communication de crisis (méthode de la roche grise, scripts de réponse courts) pour neutraliser, court-circuiter et désamorcer les attaques et provocations de la personnalité toxique au quotidien.',
  home_prog_module4_title: 'Module 4 : Le Sevrage Neuro-Émotionnel',
  home_prog_module4_desc:  'Briser l\'addiction biologique à la relation. L\'emprise crée un cycle de "shoots" chimiques destructeurs (alternance dopamine/cortisol). Ce module nettoie les ancrages neuro-biologiques profonds pour éteindre définitivement le manque, la nostalgie feinte et le risque de rechute.',
  home_prog_module5_title: 'Module 5 : Reconstruction de l\'Identité & Estime Blindée',
  home_prog_module5_desc:  'Redécouvrir qui tu es une fois le parasite relationnel extrait de ton système. Travail en profondeur de guérison sur l\'enfant intérieur, recollement des morceaux de l\'amour propre et réalignement total avec tes désirs, tes ambitions et tes valeurs fondamentales.',
  home_prog_module6_title: 'Module 6 : L\'Immunisation Définitive',
  home_prog_module6_desc:  'Création d\'un bouclier psychologique à vie. Reprogrammation de tes schémas inconscients pour détecter les profils prédateurs et manipulateurs à des kilomètres. Tu imposes tes limites de manière automatique, garantissant que plus jamais personne ne piétine ton territoire.',
  home_prog_cta:           'POSTULER AU PROGRAMME ARSENAL TACTIQUE',

  home_faq_eyebrow: 'Questions Fréquentes',
  home_faq_title:   'FAQ — Réponses Claires sur l\'Emprise et l\'Accompagnement',
  home_faq_q1:      'Comment savoir si je suis dans une relation toxique ou si le problème vient de moi ?',
  home_faq_r1:      'C’est la question centrale induite par la manipulation. Si vous passez votre temps à vous remettre en question, à ressentir une culpabilité sourde et à analyser frénétiquement les moindres variations d\'humeur de l\'autre pour éviter un conflit, vous êtes sous emprise. Le profil toxique ne se remet jamais en question. Le simple fait que vous vous posiez cette question est la preuve clinique que le dysfonctionnement ne vient pas de votre nature.',
  home_faq_q2:      'Quelle est la différence entre votre passé de thérapeute et ce coaching axé sur les résultats ?',
  home_faq_r2:      'La thérapie traditionnelle cherche principalement à comprendre le "pourquoi" et s\'inscrit souvent dans un temps long d\'introspection. Mon approche de coaching axée sur l\'Arsenal Tactique utilise mes 6 ans de bagage clinique pour identifier le mécanisme instantanément, mais bascule immédiatement sur le "comment". Nous mettons en place des protocoles d\'action, des scripts de communication et des verrous émotionnels pour obtenir des résultats factuels, mesurables et rapides.',
  home_faq_q3:      'Peut-on réellement se réparer après avoir partagé la vie d\'une personnalité psychotique ou perverse ?',
  home_faq_r3:      'Oui, absolument. Le traumatisme lié à une structure perverse ou psychotique agit comme un véritable piratage de votre système nerveux et cognitif. En appliquant un protocole strict de sevrage neuro-émotionnel et en reprogrammant vos schémas identitaires (les modules 4 et 5 de mon programme), vous pouvez non seulement retrouver votre état initial, mais développer une immunité et une clarté intérieures bien supérieures à celles que vous aviez avant la rencontre.',
  home_faq_q4:      'Mon ex-partenaire ou membre de ma famille est-il un pervers narcissique ou un psychotique ?',
  home_faq_r4:      'Poser un diagnostic psychiatrique formel demande du temps, mais les dynamiques destructrices restent identiques : absence totale d\'empathie, paranoïa constructive, inversion de la culpabilité, cycles de séduction et de destruction. Ensemble, durant nos sessions, nous analysons la typologie des comportements factuels pour adapter le protocole de défense le plus efficace possible, sans perdre de temps en spéculations stériles.',

  home_cta_title:   'Ne laisse plus un profil destructeur écrire les chapitres de ta vie',
  home_cta_desc:    'Chaque jour passé dans la confusion, le doute ou l\'attente d\'un changement qui n\'arrivera jamais est un jour volé à ta liberté et à ton avenir. Tu possèdes désormais la preuve qu\'un chemin clair, codifié et encadré par un professionnel qui a vécu cette réalité existe.',
  home_cta_invite:  'Le premier pas ne demande aucun courage, juste une décision : celle de parler à quelqu\'un qui te croit, qui te comprend, et qui sait exactement comment te sortir de là.',
  home_cta_button:  'DEMANDER MON ENTRETIEN STRATÉGIQUE PRIVÉ',


  // ── À Propos ────────────────────────────────────────────
  about_hero_title:      'Je vous aide à vous libérer.',
  about_hero_text1:      'De l\'épuisement mental et des angoisses, grâce au Rêve Éveillé Libre — une méthode d\'hypnose douce par l\'imaginaire.',
  about_hero_text2:      'Formé à l\'École du Rêve Éveillé Libre de Paris, j\'utilise la neuro-relaxation pour réactiver votre propre capacité d\'auto-guérison.',
  about_immersive_quote: '"Les ressources pour aller mieux sont déjà en vous. Mon rôle est simplement de vous aider à y accéder."',
  about_histoire_p1:     'Passionné par la complexité humaine, j\'ai consacré ma carrière à comprendre comment nous nous brisons, mais surtout comment nous nous réparons. À travers l\'analyse des rêves et l\'écoute de l\'inconscient, j\'ai développé une certitude : la résilience n\'est pas un don, c\'est une construction.',
  about_histoire_p2:     'J\'ai créé Semeur d\'Eveil pour offrir un espace différent. Un lieu où l\'on ne se contente pas de parler de ses problèmes, mais où l\'on bâtit activement les structures intérieures nécessaires pour vivre une vie alignée, souveraine et connectée à son essence.',
  about_histoire_quote:  'Je ne suis pas là pour vous porter, mais pour vous apprendre à porter votre propre monde avec élégance et force.',
  about_histoire_p3:     'Mon approche mélange la profondeur de l\'analyse des rêves, la clarté de la neuro-relaxation et la dimension sacrée de la connaissance de soi. C\'est cette alchimie qui permet de traverser ses ombres pour enfin accepter sa propre lumière.',

  // ── Footer ──────────────────────────────────────────────
  footer_image: 'https://pub-06788dc2f8884cb1bba449c00813d758.r2.dev/1781080916143-Au-dela--des-chai-nes-Matthieu.webp',

  // ── Images ──────────────────────────────────────────────
  home_photo1:     '/images/photo1.webp',
  home_photo2:     '/images/photo2.webp',
  home_photo3:     '/images/photo3.webp',
  home_photo4:     '/images/photo4.webp',
  about_portrait:  '/images/hero.webp',
  about_histoire:  '/images/about-histoire.webp',
  about_immersive: '/images/photo1.webp',
  rel_hero:        'https://images.pexels.com/photos/1366913/pexels-photo-1366913.jpeg?auto=compress&cs=tinysrgb&w=1920',
  rel_meditation:  'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg?auto=compress&cs=tinysrgb&w=800',
  rel_water:       'https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1920',
  rel_archetypes:  'https://images.pexels.com/photos/2440021/pexels-photo-2440021.jpeg?auto=compress&cs=tinysrgb&w=800',

  // ── Séance Individuelle ─────────────────────────────────
  seance_hero_eyebrow:    'Rencontre avec soi',
  seance_hero_title:      'La Séance Individuelle',
  seance_hero_subtitle:   'Une immersion de 90 minutes pour écouter les messages de votre âme, traverser vos ombres et retrouver un cap spirituel.',
  seance_content_title:   'Pourquoi choisir une séance unique ?',
  seance_content_intro:   "Parfois, le poids du quotidien ou un événement soudain est l'appel de l'âme à une pause nécessaire. Cette séance est une porte ouverte sur votre vérité intérieure, un moment pour accueillir vos ombres et laisser émerger une nouvelle clarté.",
  seance_feature_1_title: 'Format Long (90 min)',
  seance_feature_1_desc:  "Pour avoir le temps d'aller en profondeur sans précipitation.",
  seance_feature_2_title: 'Focus Résolution',
  seance_feature_2_desc:  'Concentration sur un blocage spécifique ou une émotion envahissante.',
  seance_feature_3_title: 'Outils de sortie',
  seance_feature_3_desc:  'Vous repartez avec des exercices concrets de régulation nerveuse.',
  seance_explore_title:   'Ce que nous explorons',
  seance_explore_1:       'Un rêve récent ou récurrent pour décrypter vos besoins',
  seance_explore_2:       'Les sources de votre stress ou de votre anxiété actuelle',
  seance_explore_3:       "Le décodage d'une émotion bloquante",
  seance_explore_4:       "La mise en place d'un 'kit de survie' émotionnel",
  seance_pricing_label:   'Investissement',
  seance_pricing_amount:  '140 CHF',
  seance_pricing_unit:    '/ séance',
  seance_cta_text:        'Réserver ma place',

  // ── Programme Complet ───────────────────────────────────
  programme_hero_eyebrow:   "Éveil de la Conscience",
  programme_hero_title:     'Le Programme Complet',
  programme_hero_subtitle:  "Dépassez la simple survie pour redevenir le créateur souverain de votre vie. Un voyage initiatique pour traverser vos ombres et ancrer votre lumière.",
  programme_pillars_title:  "Un voyage en 3 piliers d'éveil",
  programme_pillars_intro:  "L'accompagnement spirituel est une alchimie : nous transformons vos épreuves en une connaissance de soi profonde et radieuse.",
  programme_pillar_1_title: '01. Apaisement',
  programme_pillar_1_desc:  "La priorité absolue est de stabiliser votre système nerveux. Nous utilisons des outils de respiration et de présence pour sortir de la survie.",
  programme_pillar_2_title: '02. Analyse',
  programme_pillar_2_desc:  "L'analyse de vos rêves et de vos symboles inconscients permet de comprendre les racines du blocage et de libérer l'énergie créatrice.",
  programme_pillar_3_title: '03. Action',
  programme_pillar_3_desc:  "Enfin, nous traduisons vos prises de conscience en changements concrets dans votre quotidien pour ancrer définitivement votre nouvelle paix.",
  programme_details_title:  'Inclus dans votre parcours',
  programme_detail_1:       'Accompagnement intensif sur 3 mois',
  programme_detail_2:       '12 séances de 90 minutes',
  programme_detail_3:       'Support par message entre les séances',
  programme_detail_4:       'Plan de reconstruction personnalisé',
  programme_details_quote:  "Ce programme est un investissement en vous-même pour ne plus jamais vous sentir seul face aux épreuves.",
  programme_cta_text:       'Demander un entretien préalable',

  // ── Images ──────────────────────────────────────────────
  seance_hero:     'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=2000&auto=format&fit=crop',
  programme_hero:  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2000&auto=format&fit=crop',

  // ── Homepage Images ─────────────────────────────────────
  home_hero_bg:            'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1600',
  home_frustrations_img:   'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=800',
  home_mindset_img:        'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?q=80&w=800',
  home_accompagnement_img: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800',
  home_philosophie_img:    'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800',
  home_cta_bg:             'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600',

  // ── Homepage Section Styles ──────────────────────────────
  section_hero_bg:         'transparent',
  section_hero_theme:      'dark',
  section_hero_opacity:    '70',
  section_stats_bg:        '#0F0F0F',
  section_stats_theme:     'dark',
  section_problem_bg:      '#0A0A0A',
  section_problem_theme:   'dark',
  section_quote_bg:        '#B87333',
  section_quote_theme:     'dark',
  section_mindset_bg:      '#0F0F0F',
  section_mindset_theme:   'dark',
  section_program_bg:      '#0A0A0A',
  section_program_theme:   'dark',
  section_coach_bg:        '#0F0F0F',
  section_coach_theme:     'dark',
  section_reviews_bg:      '#0F0F0F',
  section_reviews_theme:   'dark',
  section_values_bg:       '#0A0A0A',
  section_values_theme:    'dark',
  section_cta_bg:          '#0A0A0A',
  section_cta_theme:       'dark',
  section_cta_opacity:     '70',
  section_footer_bg:       '#0F0F0F',
  section_footer_theme:    'dark',
  // ── Réseaux sociaux ─────────────────────────────────────
  social_instagram: '',
  social_linkedin: '',
  social_youtube: '',
  social_spotify: '',

  // ── Auteur (blog) ────────────────────────────────────────
  author_bio:  "Matthieu Le Tousse accompagne depuis plus de 6 ans les personnes en sortie d'emprise relationnelle. Diplômé de l'École du Rêve Éveillé Libre (EREL) et affilié à l'ADREL et à la FF2P, il aide chacun à décoder les mécanismes de manipulation et reprendre définitivement le contrôle de sa vie.",
  author_link: '/a-propos',

  navigation_menu: JSON.stringify([
    { name: "Accueil", path: "/" },
    { name: "Ateliers", path: "/ateliers" },
    { name: "Blog", path: "/blog" },
    { name: "À Propos", path: "/about" },
    { name: "Contact", path: "/contact" }
  ]),
};

// Keys whose values are image URLs — passed through proxyUrl on overrides
export const IMAGE_KEYS = new Set([
  'hero_image',
  'global_logo',
  'home_photo1', 'home_photo2', 'home_photo3', 'home_photo4',
  'about_portrait', 'about_histoire', 'about_immersive',
  'rel_hero', 'rel_meditation', 'rel_water', 'rel_archetypes',
  'seance_hero', 'programme_hero', 'home_expertise_photo',
  'home_hero_bg', 'home_frustrations_img', 'home_mindset_img',
  'home_accompagnement_img', 'home_philosophie_img', 'home_cta_bg',
  'footer_image',
  'favicon_url',
]);

export type SettingKey = keyof typeof SETTINGS_DEFAULTS;

