/**
 * Métadonnées des sections — description et champs, sans les composants.
 *
 * Ce fichier existe pour une raison précise : les composants de section sont
 * des modules client (ils utilisent `useState`). Une route serveur qui
 * importerait le registre complet tirerait tout le code client avec elle et
 * ferait échouer le build.
 *
 * Les métadonnées, elles, sont de simples données : elles peuvent être lues
 * partout — routes serveur comprises, ce dont l'import de site a besoin pour
 * décrire au modèle les sections disponibles.
 *
 * `wireframes.config.ts` les réutilise pour construire le registre, donc la
 * description d'une section n'existe qu'à un seul endroit.
 */

export interface SectionMeta {
  description: string;
  dataSchema: Record<string, string>;
}

export const SECTION_META = {
  hero_1: {
    description: 'Hero plein écran avec image de fond, titre, sous-titre italique et 2 boutons CTA',
    dataSchema: {
    text_overlap: "'none' | 'slight' | 'over' (optionnel — le texte mord sur l'image)",
    image_side: "'left' | 'right' (optionnel — côté de l'image)",
    image_width: "'third' | 'half' | 'twoThirds' (optionnel — part de largeur de l'image)",
    text_box_width: "'narrow' | 'medium' | 'wide' | 'full' (optionnel — largeur du bloc de texte)",
    eyebrow: 'string (optionnel)',
    title: 'string',
    title_italic: 'string (optionnel)',
    description: 'string (optionnel)',
    cta_primary_text: 'string (optionnel)',
    cta_primary_href: 'string (optionnel)',
    cta_secondary_text: 'string (optionnel)',
    cta_secondary_href: 'string (optionnel)',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_opacity: 'opacity (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  hero_2: {
    description: 'Hero centré sans image, texte uniquement, un seul CTA',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    min_height: 'height (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  hero_3: {
    description: 'Hero centré avec portrait en arche sous le titre, mots-clés en pastilles et 2 boutons',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    title_italic: 'string (optionnel)',
    description: 'string (optionnel)',
    items: 'string[] (pastilles, optionnel)',
    cta_primary_text: 'string (optionnel)',
    cta_primary_href: 'string (optionnel)',
    cta_secondary_text: 'string (optionnel)',
    cta_secondary_href: 'string (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  hero_4: {
    description: 'Hero éditorial : photo plein cadre, titre ancré en bas et carte d\'informations flottante',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    title_italic: 'string (optionnel)',
    description: 'string (optionnel)',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_opacity: 'opacity (optionnel)',
    card_title: 'string (optionnel)',
    card_text: 'string (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    min_height: 'height (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  hero_5: {
    description: 'Bandeau de page compact (hauteur réduite) pour les pages intérieures, avec lien discret',
    dataSchema: {
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    align: "'center' | 'left' (optionnel)",
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_opacity: 'opacity (optionnel)',
    min_height: 'height (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  intro_1: {
    description: 'Section split : image gauche + texte citation droite',
    dataSchema: {
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    eyebrow: 'string (optionnel)',
    quote: 'string',
    text: 'string',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_position: "'left' | 'right' (optionnel)",
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  features_1: {
    description: 'Section texte centré avec liste de points et citation optionnelle',
    dataSchema: {
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    quote: 'string (optionnel)',
    items: 'string[] (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    show_image: 'boolean (optionnel)',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_position: "'left' | 'right' (optionnel)",
    stretch_image: 'boolean (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  features_2: {
    description: 'Grille de 3 cartes features avec emoji/icône, titre et description',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    cards_bg_color: 'couleur (optionnel — vide = suit le thème des cartes)',
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    'cards[].title': 'string',
    'cards[].description': 'string',
    'cards[].icon': 'string emoji (optionnel)',
    'cards[].icon_image': 'image (optionnel)',
    'cards[].icon_image_bleed': 'boolean (optionnel)',
    'cards[].link_text': 'string (optionnel)',
    'cards[].link_href': 'string (optionnel)',
    show_image: 'boolean (optionnel)',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_position: "'left' | 'right' (optionnel)",
    stretch_image: 'boolean (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    cards_theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  features_3: {
    description: 'Grille 2 cartes services style pricing avec liste de bénéfices et CTA',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    cards_bg_color: 'couleur (optionnel — vide = suit le thème des cartes)',
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    'cards[].title': 'string',
    'cards[].description': 'string',
    'cards[].items': 'string[] (optionnel)',
    'cards[].cta_text': 'string (optionnel)',
    'cards[].cta_href': 'string (optionnel)',
    'cards[].badge': 'string (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  cta_1: {
    description: 'Section CTA fond sombre, centré, un seul bouton',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    cta_text: 'string',
    cta_href: 'string (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  testimonial_1: {
    description: 'Citation client/témoignage centré avec auteur et rôle',
    dataSchema: {
    quote: 'string',
    author: 'string (optionnel)',
    role: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  text_1: {
    description: 'Bloc texte simple centré avec eyebrow et titre optionnels',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    content: 'string',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  text_image_1: {
    description: 'Bloc texte enrichi (liens, titres H2, listes) avec une image à gauche ou à droite, taille d\'image et proportion des colonnes réglables',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    content: 'string',
    image_url: 'image (optionnel)',
    image_alt: 'string (optionnel)',
    image_position: "'left' | 'right' (optionnel)",
    ratio: 'ratio (optionnel)',
    image_width: 'width-percent (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  gallery_grid: {
    description: 'Galerie en grille responsive avec colonnes personnalisables et visionneuse Lightbox',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    'cards[].image': 'image',
    'cards[].title': 'string (optionnel)',
    'cards[].description': 'string (optionnel)',
    'cards[].link': 'string (optionnel)',
    columns: "'2' | '3' | '4' (optionnel)",
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  gallery_carousel: {
    description: 'Galerie en carrousel de défilement horizontal avec boutons et visionneuse Lightbox',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    'cards[].image': 'image',
    'cards[].title': 'string (optionnel)',
    'cards[].description': 'string (optionnel)',
    'cards[].link': 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  gallery_masonry: {
    description: 'Galerie en cascade (style Pinterest) avec visionneuse Lightbox',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    'cards[].image': 'image',
    'cards[].title': 'string (optionnel)',
    'cards[].description': 'string (optionnel)',
    'cards[].link': 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  faq_1: {
    description: 'Section Foire Aux Questions (FAQ) avec accordéons pliables/dépliables',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    'cards[].question': 'string',
    'cards[].answer': 'string',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  reviews_1: {
    description: 'Carrousel d\'avis clients avec étoiles, badge Google et navigation',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    eyebrow: 'string (optionnel)',
    title: 'string',
    title_bold: 'string (optionnel)',
    description: 'string (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    'cards[].name': 'string',
    'cards[].date': 'string (optionnel)',
    'cards[].rating': 'number 1-5',
    'cards[].text': 'string',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  marquee_1: {
    description: 'Bandeau défilant (marquee) avec mots personnalisés, couleur de fond, séparateur et vitesse',
    dataSchema: {
    // Déclaré comme string[] : les clés en `xxx[]` sont ignorées par
    // FieldEditor (réservées aux cartes), les mots du bandeau étaient donc
    // impossibles à modifier depuis le panneau.
    items: 'string[] (texte défilant)',
    bg_color: 'string couleur CSS (optionnel)',
    text_color: 'string couleur CSS (optionnel)',
    separator: "'★' | '●' | '•' | '◆' | '—' | '/' | '|' (optionnel)",
    speed: "'slow' | 'normal' | 'fast' (optionnel)",
    italic: 'boolean (optionnel)',
    },
  },
  pricing_1: {
    description: 'Carte tarif unique : prix, badge, liste de ce qui est inclus (2 colonnes), CTA et note de bas de carte',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    badge: 'string (optionnel)',
    price: 'string',
    price_original: 'string prix barré (optionnel)',
    price_note: 'string (optionnel)',
    items: 'string[] (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    button_style: "'primary' | 'secondary' | 'ghost' (optionnel)",
    footnote: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_color: 'string couleur CSS (optionnel)',
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  stats_1: {
    description: 'Rangée de chiffres clés (statistiques) avec valeur et légende',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    'cards[].value': 'string (ex: 500+, 98%)',
    'cards[].label': 'string',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  timeline_1: {
    description: 'Étapes numérotées d\'un processus ou d\'un parcours, alignées horizontalement',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    'cards[].title': 'string',
    'cards[].description': 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    bg_image: 'image (optionnel)',
    bg_image_opacity: 'opacity (optionnel)',
    bg_image_position: 'position (optionnel)',
    },
  },
  logos_1: {
    description: 'Bandeau de logos (partenaires, presse, "vu dans") en niveaux de gris',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    eyebrow: 'string (optionnel)',
    'cards[].image': 'image',
    'cards[].alt': 'string (optionnel)',
    'cards[].link': 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  cta_2: {
    description: 'Appel centré pleine largeur, titre et bouton',
    dataSchema: {
    title: 'string',
    description: 'string (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  cta_3: {
    description: 'Texte à gauche, bouton à droite, encadré',
    dataSchema: {
    title: 'string',
    description: 'string (optionnel)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  testimonial_2: {
    description: 'Témoignages en grille de trois colonnes',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    title: 'string (optionnel)',
    cards: 'array',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  team_1: {
    description: 'Portraits, noms et rôles en grille',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    cards: 'array',
    theme: "'light' | 'dark' (optionnel)'",
    },
  },
  contact_1: {
    description: 'Adresse, téléphone, e-mail et horaires en colonnes',
    dataSchema: {
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    address: 'string (optionnel)',
    phone: 'string (optionnel)',
    email: 'string (optionnel)',
    hours: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  steps_1: {
    description: 'Parcours en quatre étapes, de gauche à droite',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    title: 'string (optionnel)',
    cards: 'array',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  stats_2: {
    description: 'Chiffres clés sans titre, en respiration',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    cards: 'array',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  faq_2: {
    description: 'Questions et réponses toutes visibles, sans clic',
    dataSchema: {
    cards_title_size: 'taille CSS (optionnel — titre des cartes, vide = suit le texte)',
    cards_text_size: 'taille CSS (optionnel — texte des cartes, vide = taille du gabarit)',
    title: 'string (optionnel)',
    cards: 'array',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  compare_1: {
    description: 'Comparaison « avec / sans » en tableau',
    dataSchema: {
    title: 'string (optionnel)',
    left_label: 'string',
    right_label: 'string',
    rows: 'array',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  banner_1: {
    description: 'Une ligne pleine largeur : promotion ou information',
    dataSchema: {
    text: 'string',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  hero_video: {
    description: 'Hero d\'impact avec lecteur vidéo ou modale de démonstration et CTA',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    video_poster: 'image (optionnel — aperçu vidéo)',
    video_url: 'string (optionnel — lien de la vidéo YouTube/Vimeo)',
    trust_text: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  pricing_2: {
    description: 'Tableau de prix interactif avec commutateur Mensuel / Annuel et badge promotionnel',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    yearly_discount_badge: 'string (optionnel)',
    cards: 'array (plans tarifaires avec prix mensuel/annuel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  stats_3: {
    description: 'Grille de métriques et chiffres clés sous forme de cartes d\'accent',
    dataSchema: {
    title: 'string (optionnel)',
    description: 'string (optionnel)',
    cards: 'array (métriques avec valeur et libellé)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  newsletter_1: {
    description: 'Bandeau de capture d\'e-mail avec champ de saisie, note de confidentialité et avantage',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    placeholder: 'string (optionnel)',
    button_text: 'string (optionnel)',
    privacy_note: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  bento_grid_1: {
    description: 'Grille Bento asymétrique moderne (style Apple/Relume) avec cartes variées',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    cards: 'array (cartes Bento avec titre, image et chiffres)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  blog_grid_1: {
    description: 'Boucle d\'articles de blog dynamique (charge les derniers articles avec visuels, résumé, date et lien)',
    dataSchema: {
    eyebrow: 'string (optionnel)',
    title: 'string',
    description: 'string (optionnel)',
    limit: 'number (optionnel — nombre d\'articles à afficher)',
    cta_text: 'string (optionnel)',
    cta_href: 'string (optionnel)',
    theme: "'light' | 'dark' (optionnel)",
    },
  },
  hero_split_badge: {
    description: 'Hero moderne split avec badge pilule, double CTA et aperçu média sous aura lumineuse',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      description: 'string (optionnel)',
      primary_cta_text: 'string (optionnel)',
      primary_cta_href: 'string (optionnel)',
      secondary_cta_text: 'string (optionnel)',
      secondary_cta_href: 'string (optionnel)',
      image_url: 'image (optionnel)',
      theme: "'light' | 'dark' (optionnel)",
    },
  },
  features_grid_offset: {
    description: 'Grille de caractéristiques 2x2 avec puces d\'icônes colorées et checkmarks',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      description: 'string (optionnel)',
      items: 'array (atouts avec titre et description)',
      theme: "'light' | 'dark' (optionnel)",
    },
  },
  pricing_cards_modern: {
    description: 'Grille de Tarification 3-Tiers Tailwind UI avec badge formule populaire et liste d\'avantages',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      description: 'string (optionnel)',
      tiers: 'array (formules avec prix, période, description, popular et liste de features)',
      theme: "'light' | 'dark' (optionnel)",
    },
  },
  faq_accordion_modern: {
    description: 'Foire Aux Questions interactive en accordéons 2-colonnes avec réponses déroulantes',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      description: 'string (optionnel)',
      items: 'array (questions et réponses)',
      theme: "'light' | 'dark' (optionnel)",
    },
  },
  hero_turnkey_voice: {
    description: 'Hero d\'exposition Solution Clé en Main avec démonstrateur de dictée vocale en direct',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      cta_primary_text: 'string (optionnel)',
      cta_primary_href: 'string (optionnel)',
      cta_secondary_text: 'string (optionnel)',
      cta_secondary_href: 'string (optionnel)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  client_needs_matrix: {
    description: 'Matrice des besoins clients (Avant vs. Solution Clé en Main)',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      personas: 'array (métiers cibles avec title, description, badge)',
      painPoints: 'array (comparatif avant/après avec beforeTitle, beforeDesc, afterTitle, afterDesc)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  voice_showcase_1: {
    description: 'Vitrine dédiée aux commandes vocales (Interview Claude & Dictée micro)',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      voiceFeatures: 'array (fonctions vocales avec badge, title, subtitle, description, speechExample, aiResult)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  admin_mockups_gallery: {
    description: 'Galerie interactive des captations d\'écran Back-Office Admin (Caisse CO, CRM, Builder, Modules)',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      invoiceNumber: 'string (optionnel)',
      invoiceClient: 'string (optionnel)',
      invoiceAmount: 'string (optionnel)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  turnkey_bento_grid: {
    description: 'Grille Bento de tous les avantages clés de la solution tout-en-un',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      cards: 'array (cartes bento avec title, description, badge)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  turnkey_offer_pricing: {
    description: 'Présentation de l\'offre clé en main tout inclus (setup, domaine, hébergement, formation)',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      inclusions: 'array (éléments inclus avec title, desc)',
      cta_text: 'string (optionnel)',
      cta_href: 'string (optionnel)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  turnkey_faq_accordion: {
    description: 'Foire Aux Questions clients avec vouvoiement et accordéons',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      faqs: 'array (questions et réponses avec q, a)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  turnkey_steps_1: {
    description: 'Procédure didactique 1-2-3 (Setup, Utilisation, Sérénité)',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      steps: 'array (étapes avec number, title, description, badge)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
  turnkey_testimonials_1: {
    description: 'Avis et témoignages certifiés d\'indépendants suisses avec indicateurs de résultats',
    dataSchema: {
      eyebrow: 'string (optionnel)',
      title: 'string',
      title_highlight: 'string (optionnel)',
      description: 'string (optionnel)',
      testimonials: 'array (témoignages avec name, role, text, metrics, rating)',
      bg_image: 'image (optionnel)',
      bg_image_opacity: 'opacity (optionnel)',
      bg_image_position: 'position (optionnel)',
      bg_color: 'couleur (optionnel)',
      bg_pattern: 'pattern (optionnel)',
      theme: "'light' | 'dark' | 'surface' (optionnel)",
    },
  },
} as const satisfies Record<string, SectionMeta>;

export type SectionTypeName = keyof typeof SECTION_META;
